
from urllib.parse import quote
from pathlib import Path

# 设置 pics 文件夹路径
pics_dir = Path("pics")

# 创建或打开 README.md 文件
with open("README.md", "w", encoding="utf-8") as readme:
    # 写入 README 标题
    with open("README_head.md", "r", encoding="utf-8") as head:
        readme.write(head.read())
    readme.write("# Image Gallery\n\n")

    # 遍历 pics 目录下的所有子文件夹
    for folder in sorted(pics_dir.iterdir()):
        if folder.is_dir():  # 确保是文件夹
            # 写入子文件夹名称作为二级标题
            readme.write(f"## {folder.name}\n\n")

            # 遍历子文件夹中的 PNG 文件
            for image in sorted(folder.glob("*.png")):
                # 构造图片的相对路径
                image_path = image.relative_to(".")
                # 写入 Markdown 图片语法
                readme.write(f"{image.name}\n\n")
                readme.write(f"![{image.name}]({quote(str(image_path))})\n\n")

    readme.write("\n*Generated by Python script*\n")
